### PR TITLE
feat: allow arrays for somethingAt fn params

### PR DESCRIPTION
**Pull request by dkirchhof**

### CODE REVIEW

**Comment by trapcodeio** [comment]
Kindly explain why you think this feat should be included

**Comment by dkirchhof** [comment]
Just wanted to run a cron job every hour at xx:00, xx:15, xx:30 and xx:45. The expression would look like this: `0,15,30,45 * * * *`.

I figured out, that you can specify this with your library, but typescript would complain about it.
My workaround `CronTime.everyHourAt([5, 35] as any)`. With this PR you don't have to cast the parameter anymore.

**Comment by trapcodeio** [comment]
Thank You for this.
I appreciate it.

I have just published the new version.

**Comment by dkirchhof** [comment]
Thank you very much. Already updated my dependency :)

**Pull request merged**
